// This file is generated by Tools/cases_generator/jit_switch_generator.py
// from:
//   Python/bytecodes.c, Python/supernodes.c
// Do not edit!

#ifndef Py_SWITCH_JIT_H
#define Py_SWITCH_JIT_H

#include "Python.h"
#include "pycore_uop_ids.h"
#include "opcode_ids.h"
#include "jit_switch.h"



#ifdef __cplusplus
extern "C" {
#endif


#ifdef _Py_JIT


// This function always needs to be fed 1 uops
SuperNode
_JIT_INDEX(const _PyUOpInstruction *uops, uint16_t start_index) {
    switch (uops[start_index + 0].opcode) {
        default:
            return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
    }
}

#endif  // _Py_JIT

#ifdef __cplusplus
}
#endif

#endif // Py_SWITCH_JIT_H
#