// This file is generated by Tools/cases_generator/jit_switch_generator.py
// from:
//   Python/bytecodes.c, Python/supernodes.c
// Do not edit!

#include "Python.h"
#include "cpython/optimizer.h"

typedef struct {
    const uint64_t index;
    const uint16_t length;
} SuperNode;

#define SUPERNODE_MAX_DEPTH 6

//This function must always be fed 6 uops
SuperNode
_JIT_INDEX(const _PyUOpInstruction *uops, uint16_t start_index);
