// This file is generated by Tools/cases_generator/jit_switch_generator.py
// from:
//   Python/bytecodes.c, Python/supernodes.c
// Do not edit!

#ifndef Py_SWITCH_JIT_H
#define Py_SWITCH_JIT_H

#include "Python.h"
#include "pycore_uop_ids.h"
#include "opcode_ids.h"
#include "jit_switch.h"



#ifdef __cplusplus
extern "C" {
#endif


#ifdef _Py_JIT


// This function always needs to be fed 2 uops
SuperNode
_JIT_INDEX(const _PyUOpInstruction *uops, uint16_t start_index) {
    switch (uops[start_index + 0].opcode) {
        case _RETURN_VALUE:
            switch (uops[start_index + 1].opcode) {
                case _LOAD_FAST_5:
                    return (SuperNode) {.index = _RETURN_VALUE_PLUS__LOAD_FAST_5, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _RESUME_CHECK:
            switch (uops[start_index + 1].opcode) {
                case _LOAD_CONST_INLINE:
                    return (SuperNode) {.index = _RESUME_CHECK_PLUS__LOAD_CONST_INLINE, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _UNPACK_SEQUENCE_TWO_TUPLE:
            switch (uops[start_index + 1].opcode) {
                case _STORE_FAST_4:
                    return (SuperNode) {.index = _UNPACK_SEQUENCE_TWO_TUPLE_PLUS__STORE_FAST_4, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _SET_IP:
            switch (uops[start_index + 1].opcode) {
                case _BINARY_OP:
                    return (SuperNode) {.index = _SET_IP_PLUS__BINARY_OP, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _BINARY_OP:
            switch (uops[start_index + 1].opcode) {
                case _CHECK_VALIDITY:
                    return (SuperNode) {.index = _BINARY_OP_PLUS__CHECK_VALIDITY, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _BINARY_OP_ADD_FLOAT:
            switch (uops[start_index + 1].opcode) {
                case _STORE_FAST_3:
                    return (SuperNode) {.index = _BINARY_OP_ADD_FLOAT_PLUS__STORE_FAST_3, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _BINARY_OP_ADD_INT:
            switch (uops[start_index + 1].opcode) {
                case _SET_IP:
                    return (SuperNode) {.index = _BINARY_OP_ADD_INT_PLUS__SET_IP, .length = 2};
                    break;
                case _LOAD_CONST_INLINE_BORROW:
                    return (SuperNode) {.index = _BINARY_OP_ADD_INT_PLUS__LOAD_CONST_INLINE_BORROW, .length = 2};
                    break;
                case _LOAD_FAST_0:
                    return (SuperNode) {.index = _BINARY_OP_ADD_INT_PLUS__LOAD_FAST_0, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _BINARY_OP_MULTIPLY_INT:
            switch (uops[start_index + 1].opcode) {
                case _LOAD_CONST_INLINE_BORROW:
                    return (SuperNode) {.index = _BINARY_OP_MULTIPLY_INT_PLUS__LOAD_CONST_INLINE_BORROW, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _CHECK_STACK_SPACE_OPERAND:
            switch (uops[start_index + 1].opcode) {
                case _INIT_CALL_PY_EXACT_ARGS_2:
                    return (SuperNode) {.index = _CHECK_STACK_SPACE_OPERAND_PLUS__INIT_CALL_PY_EXACT_ARGS_2, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _CHECK_VALIDITY:
            switch (uops[start_index + 1].opcode) {
                case _RETURN_VALUE:
                    return (SuperNode) {.index = _CHECK_VALIDITY_PLUS__RETURN_VALUE, .length = 2};
                    break;
                case _LOAD_FAST_0:
                    return (SuperNode) {.index = _CHECK_VALIDITY_PLUS__LOAD_FAST_0, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _GUARD_BOTH_INT:
            switch (uops[start_index + 1].opcode) {
                case _BINARY_OP_ADD_INT:
                    return (SuperNode) {.index = _GUARD_BOTH_INT_PLUS__BINARY_OP_ADD_INT, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _GUARD_NOS_INT:
            switch (uops[start_index + 1].opcode) {
                case _LOAD_CONST_INLINE_BORROW:
                    return (SuperNode) {.index = _GUARD_NOS_INT_PLUS__LOAD_CONST_INLINE_BORROW, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _INIT_CALL_PY_EXACT_ARGS_2:
            switch (uops[start_index + 1].opcode) {
                case _SAVE_RETURN_OFFSET:
                    return (SuperNode) {.index = _INIT_CALL_PY_EXACT_ARGS_2_PLUS__SAVE_RETURN_OFFSET, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _JUMP_TO_TOP:
            switch (uops[start_index + 1].opcode) {
                case _TIER2_RESUME_CHECK:
                    return (SuperNode) {.index = _JUMP_TO_TOP_PLUS__TIER2_RESUME_CHECK, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _LOAD_CONST_INLINE:
            switch (uops[start_index + 1].opcode) {
                case _LOAD_FAST_0:
                    return (SuperNode) {.index = _LOAD_CONST_INLINE_PLUS__LOAD_FAST_0, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _LOAD_CONST_INLINE_BORROW:
            switch (uops[start_index + 1].opcode) {
                case _BINARY_OP_ADD_INT:
                    return (SuperNode) {.index = _LOAD_CONST_INLINE_BORROW_PLUS__BINARY_OP_ADD_INT, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _LOAD_FAST_0:
            switch (uops[start_index + 1].opcode) {
                case _GUARD_NOS_INT:
                    return (SuperNode) {.index = _LOAD_FAST_0_PLUS__GUARD_NOS_INT, .length = 2};
                    break;
                case _LOAD_FAST_1:
                    return (SuperNode) {.index = _LOAD_FAST_0_PLUS__LOAD_FAST_1, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _LOAD_FAST_1:
            switch (uops[start_index + 1].opcode) {
                case _BINARY_OP_ADD_INT:
                    return (SuperNode) {.index = _LOAD_FAST_1_PLUS__BINARY_OP_ADD_INT, .length = 2};
                    break;
                case _GUARD_BOTH_INT:
                    return (SuperNode) {.index = _LOAD_FAST_1_PLUS__GUARD_BOTH_INT, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _LOAD_FAST_3:
            switch (uops[start_index + 1].opcode) {
                case _CHECK_FUNCTION:
                    return (SuperNode) {.index = _LOAD_FAST_3_PLUS__CHECK_FUNCTION, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _PUSH_FRAME:
            switch (uops[start_index + 1].opcode) {
                case _RESUME_CHECK:
                    return (SuperNode) {.index = _PUSH_FRAME_PLUS__RESUME_CHECK, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _SAVE_RETURN_OFFSET:
            switch (uops[start_index + 1].opcode) {
                case _PUSH_FRAME:
                    return (SuperNode) {.index = _SAVE_RETURN_OFFSET_PLUS__PUSH_FRAME, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _STORE_FAST_3:
            switch (uops[start_index + 1].opcode) {
                case _JUMP_TO_TOP:
                    return (SuperNode) {.index = _STORE_FAST_3_PLUS__JUMP_TO_TOP, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _STORE_FAST_4:
            switch (uops[start_index + 1].opcode) {
                case _STORE_FAST_5:
                    return (SuperNode) {.index = _STORE_FAST_4_PLUS__STORE_FAST_5, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _STORE_FAST_5:
            switch (uops[start_index + 1].opcode) {
                case _LOAD_FAST_3:
                    return (SuperNode) {.index = _STORE_FAST_5_PLUS__LOAD_FAST_3, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        case _TIER2_RESUME_CHECK:
            switch (uops[start_index + 1].opcode) {
                case _SET_IP:
                    return (SuperNode) {.index = _TIER2_RESUME_CHECK_PLUS__SET_IP, .length = 2};
                    break;
                default:
                    return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
            }
            break;
        default:
            return (SuperNode) {.index = uops[start_index].opcode, .length = 1};
    }
}

#endif  // _Py_JIT

#ifdef __cplusplus
}
#endif

#endif // Py_SWITCH_JIT_H
#