// This file is generated by Tools/cases_generator/tier2_generator.py
// from:
//   Python/bytecodes.c, Python/supernodes.c
// Do not edit!

        #ifdef TIER_ONE
            #error "This file is for Tier 2 only"
        #endif
        #define TIER_TWO 2
        case _TO_BOOL_NONE_PLUS__POP_TOP: {
        }
        case _DYNAMIC_EXIT_PLUS__START_EXECUTOR: {
        }
        case _FOR_ITER_GEN_FRAME_PLUS__PUSH_FRAME: {
        }
        case _GUARD_NOT_EXHAUSTED_LIST_PLUS__ITER_NEXT_LIST: {
        }
        case _GUARD_NOT_EXHAUSTED_TUPLE_PLUS__ITER_NEXT_TUPLE: {
        }
        case _JUMP_TO_TOP_PLUS__TIER2_RESUME_CHECK: {
        }
        case _LOAD_FAST_2_PLUS__SET_IP: {
        }
        case _LOAD_FAST_2_PLUS__LOAD_FAST_1_PLUS__SET_IP: {
        }
        case _PUSH_FRAME_PLUS__DYNAMIC_EXIT: {
        }
        case _SAVE_RETURN_OFFSET_PLUS__PUSH_FRAME: {
        }
        case _TIER2_RESUME_CHECK_PLUS__POP_TOP: {
        }
        case _CHECK_VALIDITY_AND_SET_IP_PLUS__LOAD_ATTR_PLUS__CHECK_VALIDITY_AND_SET_IP_PLUS__BINARY_OP_PLUS__CHECK_VALIDITY_AND_SET_IP_PLUS__CHECK_FUNCTION_VERSION: {
        }
        case _BINARY_OP_PLUS__CHECK_VALIDITY_AND_SET_IP: {
        }
        case _BUILD_LIST_PLUS__LOAD_FAST_0_PLUS__GUARD_TYPE_VERSION: {
        }
        case _CALL_BUILTIN_FAST_PLUS__CHECK_PERIODIC: {
        }
        case _CALL_BUILTIN_O_PLUS__CHECK_PERIODIC: {
        }
        case _CALL_METHOD_DESCRIPTOR_O_PLUS__CHECK_PERIODIC: {
        }
        case _CALL_NON_PY_GENERAL_PLUS__CHECK_PERIODIC: {
        }
        case _CHECK_FUNCTION_EXACT_ARGS_PLUS__INIT_CALL_PY_EXACT_ARGS_1: {
        }
        case _CHECK_PERIODIC_PLUS__CHECK_VALIDITY: {
        }
        case _CHECK_PERIODIC_PLUS__CHECK_VALIDITY_AND_SET_IP: {
        }
        case _CHECK_STACK_SPACE_OPERAND_PLUS__INIT_CALL_PY_EXACT_ARGS_0_PLUS__SAVE_RETURN_OFFSET_PLUS__PUSH_FRAME: {
        }
        case _CHECK_STACK_SPACE_OPERAND_PLUS__INIT_CALL_PY_EXACT_ARGS_1_PLUS__SAVE_RETURN_OFFSET_PLUS__PUSH_FRAME: {
        }
        case _CHECK_STACK_SPACE_PLUS__INIT_CALL_PY_EXACT_ARGS_1: {
        }
        case _CHECK_VALIDITY_AND_SET_IP_PLUS__GET_ITER: {
        }
        case _CHECK_VALIDITY_AND_SET_IP_PLUS__LOAD_ATTR_PLUS__CHECK_VALIDITY_AND_SET_IP_PLUS__BINARY_OP_PLUS__CHECK_VALIDITY_AND_SET_IP: {
        }
        case _CHECK_VALIDITY_PLUS__LIST_APPEND_PLUS__JUMP_TO_TOP: {
        }
        case _CHECK_VALIDITY_PLUS__LOAD_CONST_INLINE_BORROW: {
        }
        case _CHECK_VALIDITY_PLUS__LOAD_FAST_0: {
        }
        case _CHECK_VALIDITY_PLUS__LOAD_FAST_1_PLUS__SET_IP: {
        }
        case _CHECK_VALIDITY_PLUS__LOAD_FAST_2_PLUS__SET_IP: {
        }
        case _CHECK_VALIDITY_PLUS__LOAD_FAST_4: {
        }
        case _CHECK_VALIDITY_PLUS__LOAD_FAST_5_PLUS__SET_IP: {
        }
        case _CHECK_VALIDITY_PLUS__POP_TOP: {
        }
        case _CHECK_VALIDITY_PLUS__STORE_FAST: {
        }
        case _CHECK_VALIDITY_PLUS__STORE_FAST_1: {
        }
        case _CHECK_VALIDITY_PLUS__STORE_FAST_2: {
        }
        case _CHECK_VALIDITY_PLUS__STORE_FAST_3: {
        }
        case _CHECK_VALIDITY_PLUS__STORE_FAST_4_PLUS__LOAD_FAST_3_PLUS__LOAD_FAST_4_PLUS__LOAD_FAST_2_PLUS__BUILD_TUPLE: {
        }
        case _CHECK_VALIDITY_PLUS__STORE_FAST_5_PLUS__LOAD_FAST_5: {
        }
        case _CONTAINS_OP_PLUS__CHECK_VALIDITY: {
        }
        case _GET_ITER_PLUS__CHECK_VALIDITY: {
        }
        case _GUARD_BOTH_INT_PLUS__BINARY_OP_ADD_INT: {
        }
        case _GUARD_BOTH_UNICODE_PLUS__COMPARE_OP_STR: {
        }
        case _GUARD_DORV_NO_DICT_PLUS__STORE_ATTR_INSTANCE_VALUE: {
        }
        case _GUARD_IS_FALSE_POP_PLUS__JUMP_TO_TOP: {
        }
        case _GUARD_IS_FALSE_POP_PLUS__LOAD_FAST_0: {
        }
        case _GUARD_IS_FALSE_POP_PLUS__LOAD_FAST_3_PLUS__LOAD_FAST_2_PLUS__SET_IP: {
        }
        case _GUARD_IS_NONE_POP_PLUS__LOAD_FAST_0: {
        }
        case _GUARD_IS_NOT_NONE_POP_PLUS__LOAD_FAST_3: {
        }
        case _GUARD_IS_TRUE_POP_PLUS__LOAD_CONST_INLINE_WITH_NULL_PLUS__LOAD_FAST_0_PLUS__LOAD_FAST_1: {
        }
        case _GUARD_IS_TRUE_POP_PLUS__LOAD_FAST_0: {
        }
        case _GUARD_NOT_EXHAUSTED_LIST_PLUS__ITER_NEXT_LIST_PLUS__STORE_FAST_2: {
        }
        case _GUARD_NOT_EXHAUSTED_LIST_PLUS__ITER_NEXT_LIST_PLUS__STORE_FAST_3_PLUS__LOAD_FAST_3_PLUS__LOAD_FAST_0: {
        }
        case _GUARD_NOT_EXHAUSTED_LIST_PLUS__ITER_NEXT_LIST_PLUS__STORE_FAST_4: {
        }
        case _GUARD_NOT_EXHAUSTED_LIST_PLUS__ITER_NEXT_LIST_PLUS__STORE_FAST_5: {
        }
        case _GUARD_NOT_EXHAUSTED_TUPLE_PLUS__ITER_NEXT_TUPLE_PLUS__STORE_FAST_4: {
        }
        case _GUARD_NOT_EXHAUSTED_TUPLE_PLUS__ITER_NEXT_TUPLE_PLUS__STORE_FAST_5: {
        }
        case _INIT_CALL_PY_EXACT_ARGS_0_PLUS__SAVE_RETURN_OFFSET_PLUS__PUSH_FRAME_PLUS__RESUME_CHECK: {
        }
        case _INIT_CALL_PY_EXACT_ARGS_2_PLUS__SAVE_RETURN_OFFSET_PLUS__PUSH_FRAME: {
        }
        case _ITER_NEXT_LIST_PLUS__STORE_FAST_3_PLUS__LOAD_FAST_3_PLUS__GUARD_IS_NOT_NONE_POP_PLUS__LOAD_FAST_3_PLUS__LIST_APPEND_PLUS__JUMP_TO_TOP: {
        }
        case _LIST_APPEND_PLUS__JUMP_TO_TOP: {
        }
        case _LOAD_ATTR_INSTANCE_VALUE_0_PLUS__LOAD_FAST_0: {
        }
        case _LOAD_ATTR_INSTANCE_VALUE_0_PLUS__LOAD_FAST_1: {
        }
        case _LOAD_ATTR_INSTANCE_VALUE_0_PLUS__LOAD_FAST_5: {
        }
        case _LOAD_ATTR_METHOD_NO_DICT_PLUS__LOAD_FAST_0: {
        }
        case _LOAD_ATTR_METHOD_NO_DICT_PLUS__LOAD_FAST_1: {
        }
        case _LOAD_ATTR_METHOD_NO_DICT_PLUS__LOAD_FAST_2: {
        }
        case _LOAD_ATTR_METHOD_WITH_VALUES_PLUS__LOAD_FAST_0_PLUS__CHECK_MANAGED_OBJECT_HAS_VALUES: {
        }
        case _LOAD_ATTR_METHOD_WITH_VALUES_PLUS__LOAD_FAST_1: {
        }
        case _LOAD_ATTR_PLUS__CHECK_VALIDITY_PLUS__STORE_FAST_2: {
        }
        case _LOAD_CONST_INLINE_BORROW_PLUS__STORE_FAST_2: {
        }
        case _LOAD_CONST_INLINE_PLUS__LOAD_FAST_0: {
        }
        case _LOAD_CONST_INLINE_PLUS__PUSH_NULL: {
        }
        case _LOAD_CONST_INLINE_WITH_NULL_PLUS__LOAD_FAST_0_PLUS__CHECK_MANAGED_OBJECT_HAS_VALUES: {
        }
        case _LOAD_CONST_INLINE_WITH_NULL_PLUS__LOAD_FAST_3: {
        }
        case _LOAD_CONST_INLINE_WITH_NULL_PLUS__LOAD_FAST_5_PLUS__LOAD_FAST_2: {
        }
        case _LOAD_FAST_0_PLUS__CHECK_MANAGED_OBJECT_HAS_VALUES: {
        }
        case _LOAD_FAST_0_PLUS__GUARD_TYPE_VERSION: {
        }
        case _LOAD_FAST_0_PLUS__LOAD_FAST_1: {
        }
        case _LOAD_FAST_0_PLUS__SET_IP: {
        }
        case _LOAD_FAST_1_PLUS__GUARD_TYPE_VERSION: {
        }
        case _LOAD_FAST_1_PLUS__SET_IP: {
        }
        case _LOAD_FAST_2_PLUS__GUARD_TYPE_VERSION: {
        }
        case _LOAD_FAST_2_PLUS__LOAD_CONST_INLINE_BORROW: {
        }
        case _LOAD_FAST_2_PLUS__SET_IP_PLUS__CALL_BUILTIN_O_PLUS__CHECK_PERIODIC: {
        }
        case _LOAD_FAST_2_PLUS__SET_IP_PLUS__CALL_METHOD_DESCRIPTOR_FAST_PLUS__CHECK_PERIODIC: {
        }
        case _LOAD_FAST_3_PLUS__GUARD_TYPE_VERSION: {
        }
        case _LOAD_FAST_3_PLUS__LOAD_CONST_INLINE_BORROW: {
        }
        case _LOAD_FAST_3_PLUS__LOAD_FAST_2: {
        }
        case _LOAD_FAST_3_PLUS__LOAD_FAST_4: {
        }
        case _LOAD_FAST_4_PLUS__GUARD_TYPE_VERSION: {
        }
        case _LOAD_FAST_4_PLUS__SET_IP: {
        }
        case _LOAD_FAST_5_PLUS__SET_IP: {
        }
        case _LOAD_FAST_6_PLUS__GUARD_TYPE_VERSION: {
        }
        case _LOAD_FAST_PLUS__GUARD_TYPE_VERSION: {
        }
        case _LOAD_FAST_PLUS__SET_IP: {
        }
        case _LOAD_FAST_PLUS__TO_BOOL_NONE_PLUS__POP_TOP: {
        }
        case _POP_TOP_PLUS__LOAD_FAST_1: {
        }
        case _PUSH_FRAME_PLUS__RESUME_CHECK: {
        }
        case _PUSH_NULL_PLUS__LOAD_FAST_2: {
        }
        case _RESUME_CHECK_PLUS__LOAD_FAST_0: {
        }
        case _RESUME_CHECK_PLUS__LOAD_FAST_1: {
        }
        case _RESUME_CHECK_PLUS__LOAD_FAST_2: {
        }
        case _SAVE_RETURN_OFFSET_PLUS__PUSH_FRAME_PLUS__CHECK_VALIDITY: {
        }
        case _SAVE_RETURN_OFFSET_PLUS__PUSH_FRAME_PLUS__RESUME_CHECK_PLUS__LOAD_FAST_0: {
        }
        case _SAVE_RETURN_OFFSET_PLUS__PUSH_FRAME_PLUS__RESUME_CHECK_PLUS__LOAD_FAST_1: {
        }
        case _SET_IP_PLUS__BINARY_SLICE: {
        }
        case _SET_IP_PLUS__BINARY_SUBSCR_DICT: {
        }
        case _SET_IP_PLUS__CALL_BUILTIN_FAST_PLUS__CHECK_PERIODIC: {
        }
        case _SET_IP_PLUS__CALL_METHOD_DESCRIPTOR_FAST_PLUS__CHECK_PERIODIC: {
        }
        case _SET_IP_PLUS__CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS: {
        }
        case _SET_IP_PLUS__CHECK_IS_NOT_PY_CALLABLE: {
        }
        case _SET_IP_PLUS__CONTAINS_OP_DICT: {
        }
        case _SET_IP_PLUS__LOAD_ATTR: {
        }
        case _SET_IP_PLUS__STORE_SUBSCR_DICT: {
        }
        case _SET_IP_PLUS__TO_BOOL_PLUS__CHECK_VALIDITY: {
        }
        case _STORE_FAST_1_PLUS__STORE_FAST_2: {
        }
        case _STORE_FAST_2_PLUS__CHECK_FUNCTION: {
        }
        case _STORE_FAST_2_PLUS__LOAD_FAST_0: {
        }
        case _STORE_FAST_2_PLUS__LOAD_FAST_1: {
        }
        case _STORE_FAST_2_PLUS__LOAD_FAST_2: {
        }
        case _STORE_FAST_3_PLUS__CHECK_FUNCTION: {
        }
        case _STORE_FAST_3_PLUS__LOAD_FAST_3: {
        }
        case _STORE_FAST_4_PLUS__LOAD_FAST_3: {
        }
        case _STORE_FAST_5_PLUS__CHECK_FUNCTION: {
        }
        case _STORE_FAST_7_PLUS__STORE_FAST_PLUS__LOAD_FAST_6_PLUS__GUARD_TYPE_VERSION: {
        }
        case _STORE_FAST_PLUS__LOAD_FAST_6: {
        }
        case _TIER2_RESUME_CHECK_PLUS__LOAD_CONST_INLINE_BORROW: {
        }
        case _TIER2_RESUME_CHECK_PLUS__LOAD_FAST_0: {
        }
        case _TIER2_RESUME_CHECK_PLUS__SET_IP: {
        }
        case _UNPACK_SEQUENCE_TUPLE_PLUS__STORE_FAST_6: {
        }
        case _UNPACK_SEQUENCE_TWO_TUPLE_PLUS__STORE_FAST_1: {
        }
#undef TIER_TWO
