// This file is generated by Tools/cases_generator/tier2_generator.py
// from:
//   Python/bytecodes.c, Python/supernodes.c
// Do not edit!

        #ifdef TIER_ONE
            #error "This file is for Tier 2 only"
        #endif
        #define TIER_TWO 2
        case _SWAP_PLUS__STORE_SUBSCR_LIST_INT: {
        }
        case _LOAD_FAST_PLUS__GUARD_BOTH_FLOAT: {
        }
        case _BINARY_OP_MULTIPLY_FLOAT_PLUS__BINARY_OP_ADD_FLOAT_PLUS__LOAD_FAST: {
        }
        case _BINARY_OP_MULTIPLY_FLOAT_PLUS__GUARD_NOS_FLOAT_PLUS__BINARY_OP_ADD_FLOAT_PLUS__SWAP: {
        }
        case _BINARY_OP_MULTIPLY_FLOAT_PLUS__LOAD_FAST: {
        }
        case _BINARY_SUBSCR_LIST_INT_PLUS__LOAD_FAST: {
        }
        case _COPY_PLUS__BINARY_SUBSCR_LIST_INT_PLUS__LOAD_FAST_0: {
        }
        case _GUARD_BOTH_FLOAT_PLUS__BINARY_OP_MULTIPLY_FLOAT_PLUS__STORE_FAST: {
        }
        case _GUARD_NOS_FLOAT_PLUS__BINARY_OP_ADD_FLOAT_PLUS__SWAP: {
        }
        case _GUARD_NOT_EXHAUSTED_LIST_PLUS__ITER_NEXT_LIST: {
        }
        case _ITER_NEXT_RANGE_PLUS__STORE_FAST_4: {
        }
        case _LOAD_FAST_3_PLUS__SET_IP_PLUS__GET_ITER_PLUS__CHECK_VALIDITY: {
        }
        case _LOAD_FAST_PLUS__BINARY_OP_MULTIPLY_FLOAT_PLUS__BINARY_OP_ADD_FLOAT_PLUS__LOAD_CONST_INLINE: {
        }
        case _LOAD_FAST_PLUS__BINARY_OP_MULTIPLY_FLOAT_PLUS__GUARD_NOS_FLOAT_PLUS__BINARY_OP_ADD_FLOAT: {
        }
        case _LOAD_FAST_PLUS__BINARY_OP_MULTIPLY_FLOAT_PLUS__GUARD_NOS_FLOAT_PLUS__BINARY_OP_SUBTRACT_FLOAT: {
        }
        case _LOAD_FAST_PLUS__GUARD_BOTH_FLOAT_PLUS__BINARY_OP_SUBTRACT_FLOAT: {
        }
        case _LOAD_FAST_PLUS__GUARD_NOS_FLOAT_PLUS__BINARY_OP_MULTIPLY_FLOAT: {
        }
        case _LOAD_FAST_PLUS__GUARD_TOS_FLOAT_PLUS__BINARY_OP_MULTIPLY_FLOAT: {
        }
        case _LOAD_FAST_PLUS__LOAD_CONST_INLINE_BORROW: {
        }
        case _POP_TOP_PLUS__LOAD_FAST_2_PLUS__SET_IP_PLUS__GET_ITER_PLUS__CHECK_VALIDITY: {
        }
        case _SET_IP_PLUS__BINARY_OP_PLUS__CHECK_VALIDITY: {
        }
        case _STORE_FAST_PLUS__LOAD_FAST_0: {
        }
        case _STORE_FAST_PLUS__LOAD_FAST_5: {
        }
        case _STORE_FAST_PLUS__LOAD_FAST_6: {
        }
        case _STORE_FAST_PLUS__LOAD_FAST_7: {
        }
        case _STORE_SUBSCR_LIST_INT_PLUS__LOAD_FAST_PLUS__LOAD_CONST_INLINE_BORROW: {
        }
        case _SWAP_PLUS__STORE_SUBSCR_LIST_INT_PLUS__JUMP_TO_TOP: {
        }
        case _UNPACK_SEQUENCE_LIST_PLUS__STORE_FAST_5_PLUS__STORE_FAST_6_PLUS__STORE_FAST_7: {
        }
#undef TIER_TWO
