// This file is generated by Tools/cases_generator/tier2_generator.py
// from:
//   Python/bytecodes.c, Python/supernodes.c
// Do not edit!

        #ifdef TIER_ONE
            #error "This file is for Tier 2 only"
        #endif
        #define TIER_TWO 2
        case _COPY_PLUS__TO_BOOL_BOOL: {
        }
        case _LOAD_FAST_0_PLUS__GUARD_TYPE_VERSION: {
        }
        case _GUARD_NOS_INT_PLUS__BINARY_OP_ADD_INT: {
        }
#undef TIER_TWO
